<?php
$_helper    = $this->helper('LatitudeNew\Payment\Helper\Data');
?>
    <div class="latitudepayments-popup">
        <div class="latitude-icon <?php echo ($block->showOnCart() == 0 ? 'hide' : '') ?>" >
            <span class="latitudepayments-popup__installment-text">
                <img class="lpay_snippet" src="<?=/* @escapeNotVerified */ $block->getSnippetImage() ?>" alt="LatitudePay" style="cursor: pointer;">
            </span>
            <script src="<?=$block->getUtilJs()?>"></script>
        </div>
    </div>



